image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn clean install
  - command: mvn spring-boot:run


ports:
  - port: 8080
    onOpen: open-preview



# Optional: prebuild to speed up the start time
# github:
#   prebuilds:
#     - branch: main
#       onOpen: open-preview
#       onPush: true
github:
  prebuilds:
    main: true
    pullRequests: true
    addCheck: true
    addComment: false
