image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./mvnw clean install
  - command: ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview



# Optional: prebuild to speed up the start time
github:
  prebuilds:
    - branch: main
      onOpen: open-preview
      onPush: true
