image:
  file: .gitpod.Dockerfile

tasks:
  - name: Docker Compose 
    init: docker-compose up -d
    command: |
      # Optionally wait for the services to be ready
      while ! nc -z localhost 3306; do
        echo "Waiting for database connection..."
        sleep 2
      done
  - name: Maven clean install
    init: mvn clean install
    command: mvn spring-boot:run


ports:
  - port: 8080
    onOpen: open-preview


vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot

# Optional: prebuild to speed up the start time
# github:
#   prebuilds:
#     - branch: main
#       onOpen: open-preview
#       onPush: true
github:
  prebuilds:
    main: true
    pullRequests: true
    addCheck: true
    addComment: false
