image:
  file: .gitpod.Dockerfile

tasks:
  - name: Docker Compose 
    init: docker-compose up -d
    command: docker-compose ps
  - name: Maven clean install
    init: mvn clean install -DskipTests
    command: mvn spring-boot:run


ports:
  - port: 8080
    onOpen: open-preview


vscode:
  extensions:
    - vscjava.vscode-java-pack

# Optional: prebuild to speed up the start time
# github:
#   prebuilds:
#     - branch: main
#       onOpen: open-preview
#       onPush: true
github:
  prebuilds:
    main: true
    pullRequests: true
    addCheck: true
    addComment: false
